#!/usr/bin/env bash
# llama-swap loaded-model gauge for the node-exporter textfile collector.
# Polls GET /running (cheap, does NOT trigger a model load) + /v1/models (config
# list, also load-free) and emits llamaswap_model_loaded{model} 1|0 for every
# configured model, so PromQL swap math is robust:
#   loads over time: sum(clamp_min(delta(llamaswap_model_loaded[10m]), 0))
# Same pattern as nvidia_gpu_textfile.sh (atomic mktemp+mv). jq is NOT on this
# host — python3 does the JSON.
set -uo pipefail
export LC_ALL=C
OUT="${TEXTFILE_DIR:-/var/lib/node_exporter/textfile_collector}/llamaswap.prom"
tmp="$(mktemp)"
{
  echo '# HELP llamaswap_api_up llama-swap /running endpoint reachable.'
  echo '# TYPE llamaswap_api_up gauge'
  running="$(curl -fsS -m 2 http://127.0.0.1:8081/running 2>/dev/null)"
  models="$(curl -fsS -m 2 http://127.0.0.1:8081/v1/models 2>/dev/null)"
  if [ -n "$running" ]; then
    echo 'llamaswap_api_up 1'
    echo '# HELP llamaswap_model_loaded 1 if the model is resident in llama-swap (0 = configured but not loaded).'
    echo '# TYPE llamaswap_model_loaded gauge'
    printf '%s\n%s\n' "$running" "$models" | python3 -c '
import sys, json
run = json.loads(sys.stdin.readline() or "{}")
try:
    cfg = json.loads(sys.stdin.readline() or "{}")
except Exception:
    cfg = {}
loaded = {m.get("model") for m in run.get("running") or []}
names = {m.get("id") for m in cfg.get("data") or []} | loaded
for n in sorted(x for x in names if x):
    print(f"llamaswap_model_loaded{{model=\"{n}\"}} {1 if n in loaded else 0}")'
    # Per-model token counters from the upstream llama-server (started with --metrics).
    # Only models that /running reports as "ready" are queried: /upstream/<m>/metrics on a
    # loaded model is load-free, on an unloaded one it would TRIGGER a load. This is the
    # only meter that sees direct llama-swap callers (bebop/pi/OpenClaw hitting :8081
    # without LiteLLM) — the proxy meter misses them entirely. Counters reset on every
    # (re)load; increase()/rate() absorb that. Suffix _total kept so PromQL reads as counter.
    echo '# HELP llamaswap_upstream_prompt_tokens_total Prompt tokens processed by the loaded llama-server (resets on model load).'
    echo '# TYPE llamaswap_upstream_prompt_tokens_total counter'
    echo '# HELP llamaswap_upstream_tokens_predicted_total Tokens generated by the loaded llama-server (resets on model load).'
    echo '# TYPE llamaswap_upstream_tokens_predicted_total counter'
    echo '# HELP llamaswap_upstream_prompt_seconds_total Seconds spent in prompt processing (resets on model load).'
    echo '# TYPE llamaswap_upstream_prompt_seconds_total counter'
    echo '# HELP llamaswap_upstream_tokens_predicted_seconds_total Seconds spent generating tokens (resets on model load).'
    echo '# TYPE llamaswap_upstream_tokens_predicted_seconds_total counter'
    echo '# HELP llamaswap_upstream_requests_processing Requests currently being processed by the loaded llama-server.'
    echo '# TYPE llamaswap_upstream_requests_processing gauge'
    for m in $(printf '%s' "$running" | python3 -c '
import sys, json
run = json.load(sys.stdin)
print(" ".join(x["model"] for x in run.get("running") or [] if x.get("state") == "ready"))'); do
      curl -fsS -m 2 "http://127.0.0.1:8081/upstream/${m}/metrics" 2>/dev/null | awk -v m="$m" '
        $1 == "llamacpp:prompt_tokens_total"            { printf "llamaswap_upstream_prompt_tokens_total{model=\"%s\"} %s\n", m, $2 }
        $1 == "llamacpp:tokens_predicted_total"         { printf "llamaswap_upstream_tokens_predicted_total{model=\"%s\"} %s\n", m, $2 }
        $1 == "llamacpp:prompt_seconds_total"           { printf "llamaswap_upstream_prompt_seconds_total{model=\"%s\"} %s\n", m, $2 }
        $1 == "llamacpp:tokens_predicted_seconds_total" { printf "llamaswap_upstream_tokens_predicted_seconds_total{model=\"%s\"} %s\n", m, $2 }
        $1 == "llamacpp:requests_processing"            { printf "llamaswap_upstream_requests_processing{model=\"%s\"} %s\n", m, $2 }'
    done
  else
    echo 'llamaswap_api_up 0'
  fi
} > "$tmp" && mv "$tmp" "$OUT" && chmod 644 "$OUT"
